[tox]
requires =
    tox >= 4
    tox-uv >= 1

envlist =
    py310-django40-drf{315,314,313}
    py310-django41-drf{315,314}
    py310-django42-drf{316,315}
    py310-django50-drf{316,315}
    py310-django51-drf316
    py310-django52-drf316

    py311-django40-drf{315,314,313}
    py311-django41-drf{315,314}
    py311-django42-drf{316,315}
    py311-django50-drf{316,315}
    py311-django51-drf316
    py311-django52-drf316

    py312-django40-drf315
    py312-django41-drf315
    py312-django42-drf{316,315}
    py312-django50-drf{316,315}
    py312-django51-drf316
    py312-django52-drf316

    py313-django42-drf316
    py313-django50-drf316
    py313-django51-drf316
    py313-django52-drf316

[gh]
python =
    3.10 = ci310
    3.11 = ci311
    3.12 = ci312
    3.13 = ci313

[testenv]
allowlist_externals = pytest

commands = pytest --cov=drf_yasg

deps =
    django40: Django>=4.0,<4.1
    django41: Django>=4.1,<4.2
    django42: Django>=4.2,<5
    django50: Django>=5.0,<5.1
    django51: Django>=5.1,<5.2
    django52: Django>=5.2,<6

    drf313: djangorestframework>=3.13,<3.14
    drf314: djangorestframework>=3.14,<3.15
    drf315: djangorestframework>=3.15,<3.16
    drf316: djangorestframework>=3.16,<3.17

setenv =
    PYTHONPATH = testproj
    DJANGO_SETTINGS_MODULE = testproj.settings.local
    DJANGO_SECRET_KEY = "_"

[testenv:ci310]
commands = tox -f py310 --parallel

[testenv:ci311]
commands = tox -f py311 --parallel

[testenv:ci312]
commands = tox -f py312 --parallel

[testenv:ci313]
commands = tox -f py313 --parallel
