[tox]
requires =
    tox >= 4
    tox-uv >= 1

envlist =
    py310-django40-drf{315,314,313}
    py310-django41-drf{315,314}
    py310-django42-drf{316,315}
    py310-django50-drf{316,315}
    py310-django51-drf316
    py310-django52-drf316

    py311-django40-drf{315,314,313}
    py311-django41-drf{315,314}
    py311-django42-drf{316,315}
    py311-django50-drf{316,315}
    py311-django51-drf316
    py311-django52-drf316

    py312-django40-drf315
    py312-django41-drf315
    py312-django42-drf{316,315}
    py312-django50-drf{316,315}
    py312-django51-drf316
    py312-django52-drf316

    py313-django42-drf316
    py313-django50-drf316
    py313-django51-drf316
    py313-django52-drf316

[gh]
python =
    3.10 = py310
    3.11 = py311
    3.12 = py312
    3.13 = py313

[testenv]
allowlist_externals = pytest

deps =
    django40: Django>=4.0,<4.1
    django41: Django>=4.1,<4.2
    django42: Django>=4.2,<5
    django50: Django>=5.0,<5.1
    django51: Django>=5.1,<5.2
    django52: Django>=5.2,<6

    drf313: djangorestframework>=3.13,<3.14
    drf314: djangorestframework>=3.14,<3.15
    drf315: djangorestframework>=3.15,<3.16
    drf316: djangorestframework>=3.16,<3.17

commands = pytest -n auto --cov --cov-config .coveragerc --cov-append --cov-report="" {posargs}

setenv =
    DJANGO_SETTINGS_MODULE = testproj.settings.local
    DJANGO_SECRET_KEY = ""

[testenv:py310]
commands = tox -f py310

[testenv:py311]
commands = tox -f py311

[testenv:py312]
commands = tox -f py312

[testenv:py313]
commands = tox -f py313

[pytest]
pythonpath = testproj
addopts = --ignore=node_modules
