name: Install
description: Install dependencies

inputs:
  python-version:
    description: Python version for installing dependencies
    required: true

runs:
  using: composite
  steps:
    - name: Checkout the source code
      uses: actions/checkout@v4

    - name: Set the python version
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Set up uv package caching
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ inputs.python-version }}-${{ hashFiles('uv.lock') }}
        restore-keys: ${{ runner.os }}-uv-${{ inputs.python-version }}-

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Install dependencies
      shell: bash
      run: uv sync --group all
