name: Review

on: [push, pull_request]

jobs:
  test:
    name: Run linters and tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v6

      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          python-version: ${{ matrix.python }}

      - name: Run linters
        run: uv run ruff check

      - name: Run tests
        run: uv run tox

  # Return successful statuses "Run linters and tests" for python {3.6...9}
  # These are required for branch protection rules that cannot be removed yet
  # https://github.com/axnsan12/drf-yasg/pull/922#issuecomment-2739945046
  review:
    name: Run linters and tests
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        python: ["3.6", "3.7", "3.8", "3.9"]

    steps:
      - run: echo "Deprecated tests skipped 🧪"
