# Generated by Django 2.0 on 2017-12-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main article headline', max_length=255, unique=True)),
                ('body', models.TextField(help_text='Article content', max_length=5000)),
                ('slug', models.SlugField(blank=True, help_text='Unique URL slug identifying the article', unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('cover', models.ImageField(blank=True, upload_to='article/original/')),
            ],
        ),
    ]
