# Generated by Django 3.2.16 on 2022-11-28 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_article_read_only_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='co_author',
            field=models.ForeignKey(blank=True, default=None, help_text='co-author of the article', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='co_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
